export const Icons = {
    clone: 'pi pi-clone',
    copy: 'pi pi-copy',
    edit: 'pi pi-pencil',
    inbox: 'pi pi-inbox',
    circle: 'pi pi-circle',
    checkCircle: 'pi pi-check-circle',
    delete: 'pi pi-trash',
    exportFile: 'pi pi-file-export',
    infoCircle: 'pi pi-info-circle',
    warnTriangle: 'pi pi-exclamation-triangle',
    lightningBolt: 'pi pi-bolt',
    slidersHorizontal: 'pi pi-sliders-h',
    refresh: 'pi pi-refresh',
    settings: 'pi pi-cog',
    logout: 'pi pi-sign-out',
    arrowLeft: 'pi pi-arrow-left',
    arrowRight: 'pi pi-arrow-right',
    download: 'pi pi-download',
    zoomIn: 'pi pi-search-plus',
    zoomOut: 'pi pi-search-minus',
    close: 'pi pi-times',
    eye: 'pi pi-eye',
    eyeSlash: 'pi pi-eye-slash',
    flag: 'pi pi-flag',
    flagFill: 'pi pi-flag-fill',
} as const;

